"""001

Revision ID: 24f298ec1a02
Revises: 
Create Date: 2022-09-03 21:47:39.517228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f298ec1a02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('post_index', sa.String(length=6), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=11, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=7), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_index')
    )
    op.create_table('specialties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('street', sa.String(length=256), nullable=True),
    sa.Column('house_number', sa.Integer(), nullable=True),
    sa.Column('apartment_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('patronymic', sa.String(length=256), nullable=True),
    sa.Column('specialty_id', sa.Integer(), nullable=True),
    sa.Column('admission_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deduction_percentage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('patronymic', sa.String(length=256), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctors_patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('data_appointment', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctors_patients')
    op.drop_table('patients')
    op.drop_table('doctors')
    op.drop_table('addresses')
    op.drop_table('specialties')
    op.drop_table('cities')
    # ### end Alembic commands ###
